### ISSUE TITLE
Cannot connect to API server.

### ISSUE THREAD

**Issue by shishilpatel** [anishsheela/phpresellerclub#4]
Fatal error: Uncaught Resellerclub\ApiConnectionException: Cannot connect to API server. in D:\xampp\htdocs\rs\2\src\core\Core.php:159 Stack trace: #0 D:\xampp\htdocs\rs\2\src\domain\Domain.php(30): Resellerclub\Core->callApi(0, 'domains', 'available', Array) #1 D:\xampp\htdocs\rs\2\examples\search.php(7): Resellerclub\Domain->checkAvailability('yeapmail', 'in', true) #2 {main} thrown in D:\xampp\htdocs\rs\2\src\core\Core.php on line 159

**Comment by anishsheela** [comment]
You have to modify the rc-config.sample.php to rc-config.php and make sure you whitelist the ip and wait 30 minutes. Also try using an account from demo server.
