### ISSUE TITLE
can i change dns with reseller club api ????

### ISSUE THREAD

**Issue by soly2014** [anishsheela/phpresellerclub#5]

**Comment by anishsheela** [comment]
Yes, you can. Entire API is wrapped inside it.

**Comment by anishsheela** [comment]
Sorry, My bad. Only NS and child NS can be set using API. `setNameServer`

If you can find any API calls where DNS can be added in the resellerclub API docs, let me know. I will add.

**Comment by soly2014** [comment]
thank you man for your response . i will handle it my self without any packages
